apiVersion: v1
kind: ServiceAccount
metadata:
  name: admin-user

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: view-only-user

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: editor-user
