apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: admin-binding
subjects:
  - kind: ServiceAccount
    name: admin-user
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: view-only-binding
subjects:
  - kind: ServiceAccount
    name: view-only-user
roleRef:
  kind: Role
  name: view-only
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: editor-binding
subjects:
  - kind: ServiceAccount
    name: editor-user
roleRef:
  kind: Role
  name: editor
  apiGroup: rbac.authorization.k8s.io

